version: '3'

services:
  kga:
    build: .
    container_name: knowledge_graph_agent
    ports:
      - "${API_PORT:-8000}:8000"
    env_file:
      - .env
    restart: always
    environment:
      - TZ=Europe/Brussels  # Aligned with Belgium region
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M  # Setting container limit below Neo4j's 1GB
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"